{% set name = "dolphin" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/dolphin/archive/v{{ version }}.tar.gz
  sha256: 84f02f51a2fb1d16fc06ee2a814304c3c27b28f896445c8fb93b33a81dccba46

build:
  entry_points:
    - dolphin = dolphin.cli:main
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip >=21.3
  run:
    - python >=3.8
    - isce3
    - gdal >=3.3
    - h5py >=3.6
    - hdf5 !=1.12.2 # https://github.com/SciTools/iris/issues/5187 and https://github.com/pydata/xarray/issues/7549
    - numba >=0.54
    - numpy >=1.20
    - pydantic >=2
    - pymp-pypi >=0.4.5
    - pyproj >=3.3
    - rich >=12.0
    - ruamel.yaml >=0.15
    - scipy >=1.5 # "scipy 0.16+ is required for linear algebra", numba. 1.5 is the oldest version that supports Python 3.7
    - shapely >=1.8
    - threadpoolctl >=3.0

test:
  imports:
    - dolphin
  commands:
    - pip check
    - dolphin --help
  requires:
    - pip

about:
  home: https://github.com/isce-framework/dolphin
  summary: Workflows for generating surface displacement maps using InSAR
  license: BSD-3-Clause OR Apache-2.0
  license_file: LICENSE
  doc_url: https://dolphin-insar.readthedocs.io/
  dev_url: https://github.com/isce-framework/dolphin

extra:
  recipe-maintainers:
    - scottstanie
