{% set name = "dolphin" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/dolphin/archive/v{{ version }}.tar.gz
  sha256: 23e4418d796cc69993aba3c135f4373a84b1c34db4d40e217501fa9140e2bab4

build:
  entry_points:
    - dolphin = dolphin.cli:main
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip >=21.3
  run:
    - python >=3.9
    - jax >=0.4.19
    - gdal >=3.5
    - h5py >=3.6
    - hdf5 !=1.12.2 # https://github.com/SciTools/iris/issues/5187 and https://github.com/pydata/xarray/issues/7549
    - numba >=0.56
    - numpy >=1.23
    - opera-utils >=0.1.5
    - pydantic >=2.1
    - pyproj >=3.3
    - rasterio >=1.3
    - ruamel.yaml >=0.15
    - scipy >=1.9 # "scipy 0.16+ is required for linear algebra", numba. 1.5 is the oldest version that supports Python 3.7
    - snaphu >=0.1.0
    - threadpoolctl >=3.0
    - tqdm >=4.60

test:
  imports:
    - dolphin
    - dolphin.io
    - dolphin.phase_link
    - dolphin.shp
    - dolphin.workflows
  commands:
    - dolphin --help
    - dolphin config --help
    - dolphin run --help
  requires:
    - pip

about:
  home: https://github.com/isce-framework/dolphin
  summary: Workflows for generating surface displacement maps using InSAR
  license: BSD-3-Clause OR Apache-2.0
  license_file: LICENSE
  doc_url: https://dolphin-insar.readthedocs.io/
  dev_url: https://github.com/isce-framework/dolphin

extra:
  recipe-maintainers:
    - gmgunter
    - mirzaees
    - scottstanie
