{% set name = "dolphin" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/opera-adt/dolphin/archive/v{{ version }}.tar.gz
  sha256: 13cb2416992bf51f9ae982002b8eb7beadc4b926320be7b7694b161a58a8f7af

build:
  entry_points:
    - dolphin = dolphin.cli:main
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip >=21.3
  run:
    - python >=3.8
    - gdal >=3.3
    - h5py >=3.6
    - h5netcdf >=1.0
    - isce3 >=0.8.0
    - numba >=0.54
    - numpy >=1.20
    - pydantic >=1.10
    - pymp-pypi >=0.4.5
    - pyproj >=3.2
    - rich >=12.0
    - ruamel.yaml >=0.15
    - scipy >=1.5 # "scipy 0.16+ is required for linear algebra", numba. 1.5 is the oldest version that supports Python 3.7
    - threadpoolctl >=3.0

test:
  imports:
    - dolphin
  commands:
    - pip check
    - dolphin --help
  requires:
    - pip

about:
  home: https://github.com/opera-adt/dolphin
  summary: Workflows for generating surface displacement maps using InSAR
  license: BSD-3-Clause OR Apache-2.0
  license_file: LICENSE
  doc_url: https://dolphin-insar.readthedocs.io/
  dev_url: https://github.com/opera-adt/dolphin

extra:
  recipe-maintainers:
    - scottstanie
